"""
Tables and number macros for the Delta-validity and selection analyses:

  E12  results/e12_probe_ablation_<ds>.csv  trivial baselines, in/out ablation, probe
  E13  results/e13_selection.csv            retrain-free selection and transfer
  E3o  results/e3_ssd_oracle.csv            SSD per-n alpha oracle (existing E3 rows)

Writes tab_depth.tex, tab_selection.tex, tab_ssd_oracle.tex and numbers_rebuttal.tex
into every directory given on the command line (default: paper/tables).

    python paper/make_rebuttal_tables.py            # also run by paper/make_all.py
"""
import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
DS = ["cifar10", "cifar20", "cifar100"]
DSW = {"cifar10": "Cten", "cifar20": "Ctwenty", "cifar100": "Chundred"}
DSN = {"cifar10": "CIFAR-10", "cifar20": "CIFAR-20", "cifar100": "CIFAR-100"}
OUT = {}
MACROS = []


def num(name, value, src, fmt="{:.2f}"):
    MACROS.append(f"\\newcommand{{\\{name}}}{{{fmt.format(value)}}}  % {src}")


def emit(name, body, src):
    OUT[name] = f"% Generated by paper/make_rebuttal_tables.py from results/{src} -- do not edit by hand.\n" + body


# ---------------------------------------------------------------- E12
def e12():
    frames = [pd.read_csv(os.path.join(RES, f"e12_probe_ablation_{d}.csv")) for d in DS
              if os.path.exists(os.path.join(RES, f"e12_probe_ablation_{d}.csv"))]
    d = pd.concat(frames)
    src = "e12_probe_ablation_*.csv"
    for ds in DS:
        assert (d[d.dataset == ds].groupby("method").size() == 5).all(), ds
    g = d.groupby(["dataset", "method"]).agg(
        d_r=("d_r", "mean"), d_f=("d_f", "mean"), delta=("delta", "mean"),
        agree=("agree_retain", "mean"), agree_f=("agree_forget", "mean"),
        auroc=("probe_auroc", "mean"), params=("params_damped_pct", "mean"))
    order = [("original", "Original model"), ("gold", "Retrain"),
             ("logit_mask", "Logit mask (trivial)"),
             ("ssd", "SSD"), ("lfssd", "LFSSD"), ("unact", "\\textbf{UnAct}"),
             ("unact_in", "\\quad $\\mathrm{In}_j$ only"),
             ("unact_out", "\\quad $\\mathrm{Out}_j$ only")]
    lines = []
    for m, label in order:
        cells = []
        for ds in DS:
            r = g.loc[(ds, m)]
            dl = "---" if m == "gold" else f"{r.delta:.2f}"
            cells += [f"{r.d_f:.1f}", dl, f"{r.agree_f:.1f}", f"{r.auroc:.3f}"]
        lines.append(label + " & " + " & ".join(cells) + " \\\\")
        if m in ("gold", "logit_mask", "lfssd"):
            lines.append("\\midrule")
    body = r"""\begin{table}[t]
\centering
\caption{What $\Delta$ measures (ResNet-18, full forget set, mean over the five
forget classes, selected configurations). $D_f$: forget test accuracy.
Agr$_f$: top-1 agreement with the retrained model on forget-class test images,
i.e.\ whether the forgotten images go to the same classes as under retraining.
Probe: test AUROC of a class-balanced linear probe for the forget class, trained
on the model's own penultimate training features. The logit mask zeroes the
classifier row of the class and sets its bias to $-10^4$. The last two rows replay
UnAct's per-round channel masks on only the incoming ($\mathrm{In}_j$: last
block's \texttt{conv2} filters and BatchNorm affine) or only the outgoing
($\mathrm{Out}_j$: classifier columns) parameters. Evaluated on the A10.}
\label{tab:depth}
\small
\setlength{\tabcolsep}{2.4pt}
\begin{tabular}{@{}lcccccccccccc@{}}
\toprule
& \multicolumn{4}{c}{CIFAR-10} & \multicolumn{4}{c}{CIFAR-20} & \multicolumn{4}{c}{CIFAR-100} \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(l){10-13}
Method & $D_f$ & $\Delta$ & Agr$_f$ & Probe & $D_f$ & $\Delta$ & Agr$_f$ & Probe & $D_f$ & $\Delta$ & Agr$_f$ & Probe \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    emit("tab_depth.tex", body, src)
    for ds in DS:
        w = DSW[ds]
        for m, tag in [("logit_mask", "Mask"), ("unact", "UnAct"), ("ssd", "SSD"), ("lfssd", "LFSSD"),
                       ("unact_in", "UnActIn"), ("unact_out", "UnActOut"), ("gold", "Gold"),
                       ("original", "Orig")]:
            r = g.loc[(ds, m)]
            num(f"numDepthDelta{tag}{w}", r.delta, src)
            num(f"numDepthDf{tag}{w}", r.d_f, src, "{:.1f}")
            num(f"numDepthProbe{tag}{w}", r.auroc, src, "{:.3f}")
            num(f"numDepthAgrF{tag}{w}", r.agree_f, src, "{:.1f}")
    meths = ["logit_mask", "ssd", "lfssd", "unact", "unact_in", "unact_out"]
    num("numDepthProbeMin", g[g.index.get_level_values("method").isin(meths)].auroc.min(), src, "{:.2f}")
    num("numDepthProbeGoldMin", g.xs("gold", level="method").auroc.min(), src, "{:.2f}")
    for tag, m in [("UnActIn", "unact_in"), ("UnActOut", "unact_out")]:
        s = g.xs(m, level="method").d_f
        num(f"numDepthDf{tag}Min", s.min(), src, "{:.1f}")
        num(f"numDepthDf{tag}Max", s.max(), src, "{:.1f}")


# ---------------------------------------------------------------- E13
def e13():
    d = pd.read_csv(os.path.join(RES, "e13_selection.csv"))
    src = "e13_selection.csv"
    rules = [("oracle", "Oracle ($\\min\\Delta$, needs retraining)"),
             ("rf", "Retrain-free ($D_f{=}0$, $\\max D_r$)"),
             ("lodo", "Transfer from the other two datasets"),
             ("single", "One configuration for all three")]
    lines = []
    for meth, mw in [("ssd", "SSD"), ("lfssd", "LFSSD"), ("unact", "UnAct")]:
        for i, (rule, rw) in enumerate(rules):
            cells = []
            for ds in DS:
                r = d[(d.method == meth) & (d.dataset == ds) & (d.rule == rule)].iloc[0]
                cells.append(f"{r.delta:.2f}")
            lines.append((mw if i == 0 else "") + " & " + rw + " & " + " & ".join(cells) + " \\\\")
        lines.append("\\midrule")
    lines = lines[:-1]
    body = r"""\begin{table}[t]
\centering
\caption{Choosing the operating point without a retrained model. $\Delta$ (mean
over the five forget classes) of the configuration each rule picks from the
method's full grid. For class removal the retrained model's forget accuracy is 0
by construction, so the retrain-free rule keeps the configurations with mean forget
accuracy 0 and picks the one with the highest retain accuracy; it uses a labelled
retain evaluation set (here the test split) but no retrained model. Transfer:
the configuration with the lowest mean $\Delta$ on the other two datasets. One
configuration: the lowest mean $\Delta$ over all three datasets.}
\label{tab:selection}
\small
\begin{tabular}{@{}llccc@{}}
\toprule
Method & Selection rule & CIFAR-10 & CIFAR-20 & CIFAR-100 \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    emit("tab_selection.tex", body, src)
    rf = d[d.rule == "rf"].copy()
    orc = d[d.rule == "oracle"].set_index(["method", "dataset"]).delta
    rf["gap"] = rf.apply(lambda r: r.delta - orc[(r.method, r.dataset)], axis=1)
    num("numRfSameCount", int(rf.same_as_oracle.sum()), src, "{:d}")
    num("numRfCells", len(rf), src, "{:d}")
    num("numRfMaxGap", rf.gap.max(), src)
    for meth, mw in [("ssd", "SSD"), ("lfssd", "LFSSD"), ("unact", "UnAct")]:
        s = d[(d.method == meth) & (d.rule == "single")]
        l = d[(d.method == meth) & (d.rule == "lodo")]
        num(f"numSingleMax{mw}", s.delta.max(), src)
        num(f"numSingleMean{mw}", s.delta.mean(), src)
        num(f"numLodoMax{mw}", l.delta.max(), src)
    u = d[(d.method == "unact") & (d.rule == "single")].iloc[0].config
    MACROS.append(f"\\newcommand{{\\numSingleCfgUnAct}}{{({u.replace('/', ', ')})}}  % {src}")


# ---------------------------------------------------------------- E3 oracle
def e3o():
    d = pd.read_csv(os.path.join(RES, "e3_ssd_oracle.csv"))
    src = "e3_ssd_oracle.csv"
    ns = [1, 5, 10, 25, 50, 100, 500, 1000, -1]
    lines = []
    for n in ns:
        cells = []
        for ds in DS:
            r = d[(d.dataset == ds) & (d.n == n)]
            if len(r) == 0:
                cells += ["", "", ""]
                continue
            r = r.iloc[0]
            cells += [f"{r.unact_delta:.2f}", f"{r.ssd_fixed_delta:.2f}",
                      f"{r.ssd_oracle_delta:.2f}\\,{{\\scriptsize({r.ssd_oracle_alpha:g})}}"]
        lines.append(("all" if n == -1 else str(n)) + " & " + " & ".join(cells) + " \\\\")
    body = r"""\begin{table}[t]
\centering
\caption{SSD with $\alpha$ re-selected at every forget-set size (ResNet-18,
$\Delta$, mean over the five forget classes). UnAct and SSD run at their
full-class configurations, as in Figure~\ref{fig:forget-size}. SSD-$n$ picks, at
each $n$ separately, the $\alpha$ in the range reported by the SSD paper
($\alpha\in[5,50]$; value in parentheses) with the lowest mean $\Delta$, which
requires a retrained model at every $n$; $\lambda$ and the importance batch stay at
their selected values. UnAct receives no per-$n$ tuning. From the existing
forget-set-size runs; ``all'' is the whole class (500 images on CIFAR-100).}
\label{tab:ssd-oracle}
\small
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}rccccccccc@{}}
\toprule
& \multicolumn{3}{c}{CIFAR-10} & \multicolumn{3}{c}{CIFAR-20} & \multicolumn{3}{c}{CIFAR-100} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(l){8-10}
$n$ & UnAct & SSD & SSD-$n$ & UnAct & SSD & SSD-$n$ & UnAct & SSD & SSD-$n$ \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    emit("tab_ssd_oracle.tex", body, src)
    for ds in DS:
        r = d[(d.dataset == ds) & (d.n == 5)].iloc[0]
        num(f"numOracleSSDNfive{DSW[ds]}", r.ssd_oracle_delta, src, "{:.1f}")
        num(f"numOracleUnActNfive{DSW[ds]}", r.unact_delta, src)
    small = d[d.n.isin([1, 5, 10])]
    num("numOracleSSDSmallMin", small.ssd_oracle_delta.min(), src, "{:.0f}")


# ---------------------------------------------------------------- E15
def e15():
    d = pd.read_csv(os.path.join(RES, "e15_seq_gentle.csv"))
    src = "e15_seq_gentle.csv"
    assert (d.groupby("config").order.nunique() == 5).all()
    last = d[d.request_idx == 4].groupby("config").post_retain.mean()
    num("numSeqSelDrRfive", last["p90.0_g0.3_k1"], src)
    num("numSeqGentleDrRfive", last["p99.0_g0.3_k10"], src)
    num("numSeqSingleDrRfive", last["p99.0_g0.01_k20"], src)
    num("numSeqGentleDfMax", d[d.config == "p99.0_g0.3_k10"].post_forget.max(), src, "{:.1f}")


def main(outs=None):
    outs = outs or [os.path.join(ROOT, "paper", "tables")]
    for f in (e12, e13, e3o, e15):
        try:
            f()
        except (FileNotFoundError, AssertionError, KeyError) as e:
            print(f"skipping {f.__name__}: {e!r}")
    for o in outs:
        os.makedirs(o, exist_ok=True)
        for name, body in OUT.items():
            open(os.path.join(o, name), "w").write(body)
        open(os.path.join(o, "numbers_rebuttal.tex"), "w").write(
            "% Generated by paper/make_rebuttal_tables.py -- do not edit by hand.\n" + "\n".join(MACROS) + "\n")
    print("wrote", sorted(OUT), f"and {len(MACROS)} macros to", outs)


if __name__ == "__main__":
    main(sys.argv[1:])
