"""Generate every LaTeX table of the results section directly from results/*.csv.

Run `python paper/make_tables.py`; the .tex files land in paper/tables/ and are
meant to be \\input{} rather than pasted, so a re-run of an experiment updates the
paper. Requires booktabs and multirow.

tables/numbers.tex defines one macro per number quoted in the prose
(e.g. \\numDeltaUnActCten), so the text never contains a hand-copied number.

Main body : tab_main, tab_vit
Appendix  : tab_main_full, tab_data_efficiency, tab_cost, tab_multiclass,
            tab_sequential,
            tab_e11, tab_vit_variants, tab_relearn, tab_sensitivity,
            tab_selectivity, tab_ssd_grid, tab_lfssd_grid, tab_unact_grid
"""
from __future__ import annotations

import os

import numpy as np
import pandas as pd

from common import (DATASETS, DATASET_LABEL, LFSSD_SELECTED, SSD_SELECTED, TABDIR,
                    UNACT_SELECTED, VIT_UNACT, best_per_k, load_cost_l4, load_e1,
                    load_e3_all, load_e3_raw, load_e4, load_e4_sequences, load_e5c, load_e6, load_e7,
                    load_e8, load_e9_grid, load_e11, load_main, load_vit,
                    orig_accuracy, SEQ_ORDERS)

HEAD = "%% Generated by paper/make_tables.py from results/%s -- do not edit by hand.\n"
DS_WORD = {"cifar10": "Cten", "cifar20": "Ctwenty", "cifar100": "Chundred"}
M_WORD = {"unact": "UnAct", "ssd": "SSD", "lfssd": "LFSSD", "gold": "Gold",
          "baseline": "Orig"}
METHODS = ["ssd", "lfssd", "unact"]
NAME = {"baseline": "Original model", "gold": "Retrain", "ssd": "SSD",
        "lfssd": "LFSSD", "unact": "UnAct (ours)"}

NUMBERS: list[tuple[str, str, str]] = []   # (macro, value, source)


def num(name, value, source, fmt="{:.2f}"):
    v = value if isinstance(value, str) else fmt.format(value)
    NUMBERS.append((name, v, source))
    return v


def write(name, body, source):
    os.makedirs(TABDIR, exist_ok=True)
    with open(os.path.join(TABDIR, name), "w", encoding="utf-8") as f:
        f.write(HEAD % source + body)
    print(f"  wrote tables/{name}")


def pm(m, s, d=2):
    return f"${m:.{d}f}${{\\scriptsize$\\,\\pm\\,{s:.{d}f}$}}"


def bold_if(v, cond, d=2):
    s = f"{v:.{d}f}"
    return f"\\textbf{{{s}}}" if cond else s


# ==========================================================================
# MAIN: full forget set, ResNet-18, all methods
# ==========================================================================
def _main_rows():
    m = load_main()
    out = {}
    for ds in DATASETS:
        s = m[m.dataset == ds].set_index("method")
        out[ds] = s
    return out


def table_main():
    rows = _main_rows()
    src = "e2_main_table_l4.csv + e9_baselines.csv (method lfssd)"
    lines = []
    for meth in ["baseline", "gold", "ssd", "lfssd", "unact"]:
        cells = []
        for ds in DATASETS:
            s = rows[ds]
            r = s.loc[meth]
            best = s.loc[METHODS, "score"].min()
            dr, df, mia = f"{r.d_r:.2f}", f"{r.d_f:.2f}", f"{100 * r.mia:.1f}"
            if meth == "gold":
                sc = "---"
            elif meth == "baseline":
                sc = f"{r.score:.2f}"
            else:
                sc = bold_if(r.score, np.isclose(r.score, best))
            cells += [dr, df, mia, sc]
        label = NAME[meth] if meth != "unact" else "\\textbf{UnAct} (ours)"
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
        if meth == "gold":
            lines.append(r"\midrule")
    for ds in DATASETS:
        s = rows[ds]
        for meth in ["gold", "ssd", "lfssd", "unact", "baseline"]:
            r = s.loc[meth]
            w = DS_WORD[ds] + M_WORD[meth]
            num(f"numDr{w}", r.d_r, src)
            num(f"numDf{w}", r.d_f, src)
            num(f"numMIA{w}", 100 * r.mia, src, "{:.1f}")
            if meth != "gold":
                num(f"numDelta{w}", r.score, src)
            if meth in METHODS:
                num(f"numParams{w}", r.damped, src)
        num(f"numDrGapUnAct{DS_WORD[ds]}", s.loc["gold", "d_r"] - s.loc["unact", "d_r"], src)
        # Original model's overall fp32 test accuracy (the Setup paragraph).
        num(f"numOrigAcc{DS_WORD[ds]}", s.loc["baseline", "overall"], src)

    body = r"""\begin{table}[t]
\centering
\caption{Removing one class with the full forget set (ResNet-18). Mean over the
five forget classes. $D_r$ and $D_f$ are test accuracies on the
retained and forgotten classes, MIA is the membership-inference rate on the
forget set, and $\Delta = |D_r - D_r^{\mathrm{gold}}| + |D_f - D_f^{\mathrm{gold}}|$
(Eq.~\ref{eq:score}) is the distance to the retrained model, computed per class
and then averaged; lower is better and the best unlearning method is in bold.
Every method runs at the single operating point its grid selected (90
configurations for SSD and LFSSD, 100 for UnAct). UnAct uses no labels, no
gradients and no retain data; SSD uses all three, LFSSD uses gradients and the
full training set. Standard deviations, Avg.\ Gap and the fraction of modified
parameters are in Table~\ref{tab:main-full}.}
\label{tab:main}
\small
\setlength{\tabcolsep}{2.9pt}
\begin{tabular}{@{}lcccccccccccc@{}}
\toprule
& \multicolumn{4}{c}{CIFAR-10} & \multicolumn{4}{c}{CIFAR-20} & \multicolumn{4}{c}{CIFAR-100} \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(l){10-13}
Method & $D_r$ & $D_f$ & MIA & $\Delta\!\downarrow$ & $D_r$ & $D_f$ & MIA & $\Delta\!\downarrow$ & $D_r$ & $D_f$ & MIA & $\Delta\!\downarrow$ \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_main.tex", body, src)


def table_main_full():
    rows = _main_rows()
    blocks = []
    for ds in DATASETS:
        s = rows[ds]
        block = []
        for meth in ["baseline", "gold", "ssd", "lfssd", "unact"]:
            r = s.loc[meth]
            cfg = {"baseline": "---", "gold": "100 epochs"}.get(
                meth, r.config.replace("layer4_last_", "").replace("_", ", "))
            sc = "---" if meth == "gold" else f"{r.score:.2f}{{\\scriptsize$\\,\\pm\\,{r.score_sd:.2f}$}}"
            ag = "---" if meth == "gold" else f"{r.avg_gap:.2f}"
            dm = "---" if meth in ("baseline", "gold") else f"{r.damped:.2f}"
            dev = "A10" if "A10" in r.devices else "L4"
            block.append(f"  & {NAME[meth]} & \\texttt{{\\scriptsize {cfg}}} & "
                         f"{pm(r.d_r, r.d_r_sd)} & {pm(r.d_f, r.d_f_sd)} & "
                         f"{pm(100 * r.mia, 100 * r.mia_sd, 1)} & {sc} & {ag} & {dm} & {dev} \\\\")
        block[0] = f"\\multirow{{5}}{{*}}{{{DATASET_LABEL[ds]}}}" + block[0]
        blocks.append("\n".join(block))
    body = r"""\begin{table}[t]
\centering
\caption{Full version of Table~\ref{tab:main}: mean $\pm$ s.d.\ over the five
forget classes. Avg.\ Gap follows \citet{fan2024salunempoweringmachineunlearning} over the three terms we
record, $|\Delta D_f|$, $|\Delta D_r|$ and $|\Delta\mathrm{MIA}|$ with MIA in
points; it omits their training-set retain accuracy. Because every unlearning
method drives MIA to about 0 against a retrained model at 7--30, the MIA term
dominates Avg.\ Gap. ``Params'' is the percentage of parameters modified. LFSSD
rows on CIFAR-20 and CIFAR-100 were evaluated on an A10 rather than the L4; the
two devices differ by at most one test image on the same checkpoint.}
\label{tab:main-full}
\scriptsize
\setlength{\tabcolsep}{2.6pt}
\begin{tabular}{@{}llcccccccc@{}}
\toprule
 & Method & Configuration & $D_r$ & $D_f$ & MIA & $\Delta\downarrow$ & Avg.\ Gap$\downarrow$ & Params (\%) & Eval \\
\midrule
""" + "\n\\midrule\n".join(blocks) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_main_full.tex", body, "e2_main_table_l4.csv + e9_baselines.csv")


# ==========================================================================
# Forget-set size (E3)
# ==========================================================================
def _nstar(s):
    b = s.score.min()
    return int(s[s.score <= 2 * b].forget_n.min())


def table_data_efficiency():
    data = load_e3_all()
    src = "e3_forget_size.csv (unact, ssd) + e3_lfssd_forget_size.csv"
    meths = [m for m in METHODS if m in data]
    ns = sorted(set(data["unact"].forget_n))
    lines = []
    for n in ns:
        cells = []
        for ds in DATASETS:
            vals = {}
            for m in meths:
                d = data[m]
                r = d[(d.dataset == ds) & (d.forget_n == n)]
                vals[m] = r.score.iloc[0] if len(r) else None
            present = [v for v in vals.values() if v is not None]
            best = min(present) if present else None
            for m in meths:
                v = vals[m]
                cells.append("---" if v is None else bold_if(v, np.isclose(v, best)))
        lines.append(f"{n} & " + " & ".join(cells) + r" \\")
    tail = []
    for ds in DATASETS:
        for m in meths:
            d = data[m]
            s = d[d.dataset == ds]
            ns_ = _nstar(s)
            tail.append(str(ns_))
            num(f"numNstar{M_WORD[m]}{DS_WORD[ds]}", str(ns_), src)
    lines.append(r"\midrule")
    lines.append(r"$n^\star$ & " + " & ".join(tail) + r" \\")
    # Numbers quoted in the text.
    for ds in DATASETS:
        for m in meths:
            d = data[m]
            s = d[d.dataset == ds].set_index("forget_n")
            for n in (1, 5, 10, 25):
                if n in s.index:
                    num(f"numDelta{M_WORD[m]}{DS_WORD[ds]}N{ {1:'one',5:'five',10:'ten',25:'twentyfive'}[n] }".replace(" ", ""),
                        s.loc[n, "score"], src)
            num(f"numMinDr{M_WORD[m]}{DS_WORD[ds]}", s.d_r.min(), src)
    raw = load_e3_raw()
    raw["drop"] = raw.gold_retain - raw.post_retain
    worst = raw.groupby(["dataset", "method"])["drop"].max()
    for ds in DATASETS:
        for m in meths:
            num(f"numWorstDrop{M_WORD[m]}{DS_WORD[ds]}", worst.loc[(ds, m)], src)
    un = data["unact"]
    full = un.groupby("dataset").apply(lambda s: s.sort_values("forget_n").score.iloc[-1],
                                       include_groups=False)
    dev = max((un[(un.dataset == ds) & (un.forget_n >= 25)].score - full[ds]).abs().max()
              for ds in DATASETS)
    num("numUnActMaxDevFromFullNgeTwentyfive", dev, src)
    num("numUnActRunsEthree", str(int(len(raw[raw.method == "unact"]))), src)

    ncol = len(meths)
    heads = " & ".join({"ssd": "SSD", "lfssd": "LFSSD", "unact": "UnAct"}[m] for m in meths)
    cm = "".join(f"\\cmidrule(lr){{{2 + i * ncol}-{1 + (i + 1) * ncol}}}" for i in range(3))
    body = r"""\begin{table}[t]
\centering
\caption{Distance to the retrained model $\Delta$ against the number of forget
images $n$ each method is shown; the best method in each cell group is in bold.
Every method runs at its single selected configuration at every $n$. The class
being removed and the retain set are fixed, and SSD and LFSSD always receive
their importance pass over the full training set, so $n$ measures only how much
evidence a method needs to locate the class. The last $n$ of each dataset is the
whole class. $n^\star$ is the smallest $n$ at which a method comes within
$2\times$ of its own best $\Delta$.}
\label{tab:data-efficiency}
\small
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{@{}r""" + "c" * (3 * ncol) + r"""@{}}
\toprule
& \multicolumn{""" + str(ncol) + r"""}{c}{CIFAR-10} & \multicolumn{""" + str(ncol) + r"""}{c}{CIFAR-20} & \multicolumn{""" + str(ncol) + r"""}{c}{CIFAR-100} \\
""" + cm + "\n$n$ & " + " & ".join([heads] * 3) + r""" \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_data_efficiency.tex", body, src)


# ==========================================================================
# Cost (serialised L4, paired sessions)
# ==========================================================================
def table_cost():
    c = load_cost_l4()
    src = "cost_breakdown_l4.csv + cost_breakdown_l4_k1.csv + cost_breakdown_l4_k5.csv"
    lines = []
    for ds in DATASETS:
        s = c[c.dataset == ds].sort_values("iters")
        block = []
        for _, r in s.iterrows():
            sel = (r.percentile, r.gamma, int(r.iters)) == UNACT_SELECTED[ds]
            share = 100 * r.ssd_full / r.ssd_cold
            ra, rc = r.ssd_amort / r.unact_s, r.ssd_cold / r.unact_s
            k = int(r.iters)
            tag = "" if not sel else "$^\\dagger$"
            block.append(
                f" & {k}{tag} & \\texttt{{\\scriptsize p{r.percentile:g}, $\\gamma${r.gamma:g}}} & "
                f"{r.score:.2f} & {r.unact_s:.2f} & {r.ssd_amort:.2f} & {r.ssd_cold:.1f} & "
                f"{share:.0f} & {bold_if(ra, ra > 1)}$\\times$ & {rc:.0f}$\\times$ \\\\")
            kw = {1: "Kone", 5: "Kfive", 20: "Ktwenty"}[k]
            num(f"numTimeUnAct{DS_WORD[ds]}{kw}", r.unact_s, src)
            num(f"numTimeSSDAmort{DS_WORD[ds]}{kw}", r.ssd_amort, src)
            num(f"numTimeSSDCold{DS_WORD[ds]}{kw}", r.ssd_cold, src, "{:.1f}")
            num(f"numSpeedupAmort{DS_WORD[ds]}{kw}", ra, src, "{:.1f}")
            num(f"numSpeedupCold{DS_WORD[ds]}{kw}", rc, src, "{:.0f}")
            num(f"numDeltaUnAct{DS_WORD[ds]}{kw}", r.score, src)
            num(f"numFullShare{DS_WORD[ds]}{kw}", share, src, "{:.0f}")
        block[0] = f"\\multirow{{{len(block)}}}{{*}}{{{DATASET_LABEL[ds]}}}" + block[0]
        lines.append("\n".join(block))
    body = r"""\begin{table}[t]
\centering
\caption{Wall-clock cost on one L4, serialised, full forget class (class 3),
warm-up repeat discarded, mean of the remaining repeats. For each $k$, UnAct runs
the best configuration of its grid with that number of rounds
($^\dagger$: the selected configuration); its $\Delta$ is the five-class grid
value. SSD runs its selected configuration in the same session, so each ratio is
paired. ``Amortised'' credits SSD's importance pass over the full training set as
precomputed and reusable, which its paper allows; that pass is the listed share
of SSD's cold cost. Ratios above 1 mean UnAct is faster; bold marks the
settings where it is faster even than amortised SSD.}
\label{tab:cost}
\small
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{@{}llccccccrr@{}}
\toprule
& & & & UnAct & \multicolumn{2}{c}{SSD (s)} & full-$D$ & \multicolumn{2}{c}{UnAct speed-up} \\
\cmidrule(lr){6-7}\cmidrule(l){9-10}
Dataset & $k$ & config & $\Delta$ & (s) & amortised & cold & share (\%) & vs.\ amort. & vs.\ cold \\
\midrule
""" + "\n\\midrule\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_cost.tex", body, src)
    # One-round Delta vs selected Delta (grid values).
    bk = best_per_k()
    e6 = load_e6()
    for ds in DATASETS:
        p, g, k = UNACT_SELECTED[ds]
        sel = e6[(e6.dataset == ds) & (e6.percentile == p) & (e6.gamma == g)
                 & (e6.iters == k)].score.iloc[0]
        one = bk[(bk.dataset == ds) & (bk.iters == 1)].score.iloc[0]
        num(f"numKoneMinusSelected{DS_WORD[ds]}", one - sel, "e6_unact_grid.csv")


# ==========================================================================
# Multi-class and sequential (E4), selected single-class configs only
# ==========================================================================
def table_multiclass():
    e4 = load_e4()
    src = "e4_multiclass.csv (rows at the selected single-class configuration)"
    lines = []
    for mode, ks in [("sequential", [1, 2, 3, 5]), ("simultaneous", [1, 2, 3, 5])]:
        block = []
        for ds in DATASETS:
            cells = []
            for meth in ("ssd", "unact"):
                s = e4[(e4["mode"] == mode) & (e4.dataset == ds) & (e4.method == meth)]
                for k in ks:
                    r = s[s.k == k]
                    cells.append("---" if len(r) == 0 or pd.isna(r.score.iloc[0])
                                 else f"{r.score.iloc[0]:.2f}")
                last = s[s.k == 5].iloc[0]
                cells.append(f"{last.post_retain:.1f}/{last.post_forget:.1f}")
                for k in ks:
                    r = s[s.k == k]
                    if len(r) and not pd.isna(r.score.iloc[0]):
                        kw = {1: "one", 2: "two", 3: "three", 5: "five"}[k]
                        num(f"num{mode.capitalize()}{M_WORD[meth]}{DS_WORD[ds]}K{kw}",
                            r.score.iloc[0], src)
                num(f"num{mode.capitalize()}Dr{M_WORD[meth]}{DS_WORD[ds]}Kfive",
                    last.post_retain, src)
                num(f"num{mode.capitalize()}Df{M_WORD[meth]}{DS_WORD[ds]}Kfive",
                    last.post_forget, src)
                if mode == "sequential":
                    num(f"numSequentialDrop{M_WORD[meth]}{DS_WORD[ds]}Kfive",
                        last.gold_retain - last.post_retain, src)
            block.append(f" & {DATASET_LABEL[ds]} & " + " & ".join(cells) + r" \\")
        block[0] = f"\\multirow{{3}}{{*}}{{\\rotatebox{{90}}{{\\scriptsize {mode}}}}}" + block[0]
        lines.append("\n".join(block))
        # gold D_r after all five requests
    body = r"""\begin{table}[t]
\centering
\caption{Removing several classes, with each method at its selected single-class
configuration (no re-tuning for the task). \emph{Sequential}: one class per
request, applied to the already-edited model; the column is the number of
requests so far. \emph{Simultaneous}: all $k$ classes in one request. $\Delta$ is
measured against a model retrained without all $k$ classes; four-class retrained
models were not trained, so $k=4$ is omitted. The last column of each method is
$D_r/D_f$ after five classes. Sequential: the first of the five class orders of
Table~\ref{tab:sequential}, the only one with retrained references. Seed 42.}
\label{tab:multiclass}
\scriptsize
\setlength{\tabcolsep}{2.6pt}
\begin{tabular}{@{}llccccrccccr@{}}
\toprule
& & \multicolumn{5}{c}{SSD} & \multicolumn{5}{c}{UnAct (ours)} \\
\cmidrule(lr){3-7}\cmidrule(l){8-12}
& Dataset & $k{=}1$ & 2 & 3 & 5 & $D_r/D_f$ & $k{=}1$ & 2 & 3 & 5 & $D_r/D_f$ \\
\midrule
""" + "\n\\midrule\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_multiclass.tex", body, src)
    seq = e4[(e4["mode"] == "sequential") & (e4.k == 5) & (e4.method == "unact")]
    for _, r in seq.iterrows():
        num(f"numSequentialGoldDr{DS_WORD[r.dataset]}Kfive", r.gold_retain, src)


REQ_WORD = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five"}


def table_sequential():
    """Sequential requests over every complete pre-registered class order:
    per-request mean +/- sd over the orders of D_f (on all requested classes)
    and D_r, for both methods at their selected single-class configuration."""
    seq, missing = load_e4_sequences(verbose=False)
    orig = orig_accuracy()
    src = ("e4_multiclass.csv (selected _ov rows, first order) + e4b_seq_orders.csv "
           "(selected configs)")
    lines = []
    for ds in DATASETS:
        s = seq[seq.dataset == ds]
        n_ord = s.order.nunique()
        num(f"numSeqOrders{DS_WORD[ds]}", str(n_ord), src)
        block = []
        for r in range(1, 6):
            cells = []
            for meth in ("ssd", "unact"):
                t = s[(s.method == meth) & (s.request == r)]
                for col, tag in (("post_forget", "Df"), ("post_retain", "Dr")):
                    m_, sd = t[col].mean(), t[col].std(ddof=1) if len(t) > 1 else 0.0
                    cells.append(pm(m_, sd, 1))
                    num(f"numSeq{tag}{M_WORD[meth]}{DS_WORD[ds]}R{REQ_WORD[r]}", m_, src, "{:.1f}")
                    num(f"numSeq{tag}Sd{M_WORD[meth]}{DS_WORD[ds]}R{REQ_WORD[r]}", sd, src, "{:.1f}")
                if col == "post_retain":
                    num(f"numSeqDrWorst{M_WORD[meth]}{DS_WORD[ds]}R{REQ_WORD[r]}",
                        t[col].min(), src, "{:.1f}")
            block.append(f" & {r} & " + " & ".join(cells) + r" \\")
        orders = "; ".join("(" + ",".join(map(str, o)) + ")" for o in SEQ_ORDERS[ds]
                           if ",".join(map(str, o)) in set(s.order))
        block[0] = (f"\\multirow{{5}}{{*}}{{\\shortstack[l]{{{DATASET_LABEL[ds]}\\\\"
                    f"\\scriptsize {n_ord} order{'s' if n_ord != 1 else ''}\\\\\\scriptsize orig.\\ {orig[ds]:.2f}}}}}"
                    + block[0])
        lines.append("\n".join(block))
        lines[-1] += f"\n\\multicolumn{{6}}{{@{{}}l}}{{\\tiny orders: {orders}}} \\\\"
    num("numSeqOrdersMissing", str(len(missing)), src)
    body = r"""\begin{table}[t]
\centering
\caption{Sequential deletion requests over five class orders per dataset, drawn
at random before running
(one class per request, each applied to the already-edited model). Mean
$\pm$ sd over the class orders of the forget accuracy on \emph{all} classes
requested so far ($D_f$) and the retain accuracy ($D_r$), both in \%. Both
methods run at their selected single-class configuration, with no re-tuning;
SSD recomputes its importances on the current model at every request. Most
prefixes have no retrained model, so the reference is the original model's
test accuracy over all classes (``orig.''); its accuracy on the remaining classes
shifts as classes are removed. The first order is the one of
Table~\ref{tab:multiclass} (evaluated on an A10); the others were evaluated on an
L4. Seed 42.}
\label{tab:sequential}
\scriptsize
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{@{}llcccc@{}}
\toprule
& & \multicolumn{2}{c}{SSD} & \multicolumn{2}{c}{UnAct (ours)} \\
\cmidrule(lr){3-4}\cmidrule(l){5-6}
Dataset & Request & $D_f$ & $D_r$ & $D_f$ & $D_r$ \\
\midrule
""" + "\n\\midrule\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_sequential.tex", body, src)


# ==========================================================================
# ViT-B/16 (exploratory E5b stage 2)
# ==========================================================================
def table_vit():
    u, s = load_vit()
    scope, p, g, k = VIT_UNACT
    un = u[(u.scope == scope) & (u.percentile == p) & (u.gamma == g) & (u.iters == k)]
    src = "e5b_vit_explore.csv (profile_n 0) + e5b_vit_ssd_explore.csv (eval_retain_n 0)"
    assert un.forget_class.nunique() == 5 and s.forget_class.nunique() == 5
    m = un.merge(s, on="forget_class", suffixes=("_u", "_s"))
    closer_u = int((m.score_u < m.score_s).sum())
    rows = []
    rows.append(("Original model", un.base_retain.mean(), un.base_forget.mean(), None,
                 un.base_retain.min(), None, None))
    rows.append(("Retrain", un.gold_retain.mean(), un.gold_forget.mean(), None,
                 un.gold_retain.min(), None, None))
    for lab, d, cl, key in [("SSD", s, 5 - closer_u, "ssd"),
                            ("\\textbf{UnAct} (ours)", un, closer_u, "unact")]:
        rows.append((lab, d.post_retain.mean(), d.post_forget.mean(), d.score.mean(),
                     d.post_retain.min(), cl, d.params_damped_pct.mean()))
        w = M_WORD[key]
        num(f"numVitDelta{w}", d.score.mean(), src)
        num(f"numVitDeltaMedian{w}", d.score.median(), src)
        num(f"numVitDr{w}", d.post_retain.mean(), src)
        num(f"numVitDf{w}", d.post_forget.mean(), src)
        num(f"numVitWorstDr{w}", d.post_retain.min(), src)
        num(f"numVitParams{w}", d.params_damped_pct.mean(), src)
        num(f"numVitCloser{w}", str(cl), src)
        # Excluding class 3 (UnAct's configuration was chosen on class 3).
        num(f"numVitDeltaExclThree{w}", d[d.forget_class != 3].score.mean(), src)
        num(f"numVitTime{w}", d.method_time_s.mean(), src, "{:.0f}")
    num("numVitGoldDr", un.gold_retain.mean(), src)
    num("numVitOrigDr", un.base_retain.mean(), src)
    best = min(r[3] for r in rows if r[3] is not None)
    lines = []
    for lab, dr, df, sc, wdr, cl, par in rows:
        scs = "---" if sc is None else bold_if(sc, np.isclose(sc, best))
        cls = "---" if cl is None else f"{cl}/5"
        pars = "---" if par is None else f"{par:.2f}"
        lines.append(f"{lab} & {dr:.2f} & {df:.2f} & {scs} & {wdr:.1f} & {cls} & {pars} \\\\")
        if lab == "Retrain":
            lines.append(r"\midrule")
    body = r"""\begin{table}[t]
\centering
\caption{Removing one class from ViT-B/16 on CIFAR-10 (ImageNet-1k pre-trained,
fine-tuned), mean over the same five forget classes, fp32 on the full test
split. UnAct scores the MLP neurons of blocks 9--12 at the class token
(Eq.~\ref{eq:vit-score}; $p=85$, $\gamma=0.1$, $k=5$). This configuration was
chosen on one class (class 3) and then run on all five; unlike the ResNet grids
it was not fixed in advance. SSD runs its best setting from a grid over
$\alpha\in[2,50]$ and $\lambda$ with importance batch 128 ($\alpha=5$,
$\lambda=0.1$). ``Worst $D_r$'' is the lowest retain accuracy over the five
classes and ``closer'' counts the classes on which the method has the smaller
$\Delta$. Per-class results are in Table~\ref{tab:vit-variants}.}
\label{tab:vit}
\small
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}lcccccc@{}}
\toprule
Method & $D_r$ & $D_f$ & $\Delta\!\downarrow$ & worst $D_r$ & closer & Params (\%) \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_vit.tex", body, src)


def table_vit_variants():
    u, s = load_vit()
    src = "e5b_vit_explore.csv (profile_n 0) + e5b_vit_ssd_explore.csv (eval_retain_n 0)"
    desc = {"ffn_dla_last4": "MLP, blocks 9--12, class-token logit score",
            "ffn_dla_last2": "MLP, blocks 11--12, class-token logit score",
            "ffn_pos_last4": "MLP, blocks 9--12, class-token activation",
            "head_dla": "classifier input only, logit score"}
    lines = []
    for scope in ["ffn_dla_last4", "ffn_dla_last2", "ffn_pos_last4"]:
        d = u[u.scope == scope]
        if len(d) == 0:
            continue
        r0 = d.iloc[0]
        per = " & ".join(f"{d[d.forget_class == c].score.iloc[0]:.1f}"
                         for c in sorted(d.forget_class.unique()))
        tag = " (reported)" if scope == VIT_UNACT[0] else ""
        lines.append(f"UnAct & {desc[scope]}{tag} & p{r0.percentile:g}, $\\gamma${r0.gamma:g}, "
                     f"$k${int(r0.iters)} & {d.post_retain.mean():.2f} & "
                     f"{d.post_forget.mean():.2f} & {d.score.mean():.2f} & {per} & "
                     f"{d.params_damped_pct.mean():.3f} \\\\")
        num(f"numVitVariant{scope.replace('_', '').replace('ffn','Ffn').replace('dla','Dla').replace('pos','Pos').replace('last4','Lastfour').replace('last2','Lasttwo').replace('head','Head')}",
            d.score.mean(), src)
    per = " & ".join(f"{s[s.forget_class == c].score.iloc[0]:.1f}"
                     for c in sorted(s.forget_class.unique()))
    lines.append(r"\midrule")
    lines.append(f"SSD & importance-weighted dampening & $\\alpha$5, $\\lambda$0.1, b128 & "
                 f"{s.post_retain.mean():.2f} & {s.post_forget.mean():.2f} & "
                 f"{s.score.mean():.2f} & {per} & {s.params_damped_pct.mean():.3f} \\\\")
    per_dr = ", ".join(f"{c}: {s[s.forget_class == c].post_retain.iloc[0]:.1f}/"
                       f"{s[s.forget_class == c].post_forget.iloc[0]:.1f}"
                       for c in sorted(s.forget_class.unique()))
    body = r"""\begin{table}[t]
\centering
\caption{ViT-B/16 score variants. Each UnAct variant's configuration
was chosen on class 3 (bf16, 2{,}000 retain images) and then run on all five
classes at fp32 on the full test split; the rows here are that second stage.
Columns 7--11 are $\Delta$ per forget class. The activation-magnitude score at
the class token fails (row 3), which is the reason for the logit score of
Eq.~\eqref{eq:vit-score}. SSD per class ($D_r/D_f$): """ + per_dr + r""".}
\label{tab:vit-variants}
\scriptsize
\setlength{\tabcolsep}{2.4pt}
\begin{tabular}{@{}lllccccccccc@{}}
\toprule
& Units and score & Config & $D_r$ & $D_f$ & $\Delta$ & c0 & c2 & c3 & c5 & c8 & Params (\%) \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_vit_variants.tex", body, src)


# ==========================================================================
# Held-out classes SSD's paper reports failures on (E11)
# ==========================================================================
def table_e11():
    e = load_e11()
    src = "e11_hard_classes_{ssd,lfssd,unact}.csv"
    names = {("cifar100", 2): "CIFAR-100 baby", ("cifar100", 40): "CIFAR-100 lamp",
             ("cifar20", 5): "CIFAR-20 electrical dev."}
    lines = []
    for (ds, c), lab in names.items():
        cells = []
        s = e[(e.dataset == ds) & (e.forget_class == c)].set_index("method")
        best = s.score.min()
        for m in METHODS:
            r = s.loc[m]
            cells += [f"{r.d_r:.2f}/{r.d_f:.2f}", bold_if(r.score, np.isclose(r.score, best)),
                      f"{r.oracle_score:.2f}"]
        lines.append(f"{lab} & {s.loc['ssd', 'gold_r']:.2f} & " + " & ".join(cells) + r" \\")
    raw = pd.read_csv(os.path.join(os.path.dirname(TABDIR), "..", "results",
                                   "e11_hard_classes_ssd.csv"))
    raw["score"] = (raw.post_retain - raw.gold_retain).abs() + (raw.post_forget - raw.gold_forget).abs()
    dflt = raw[(raw.alpha == 10) & (raw["lambda"] == 1)]
    dl = "; ".join(f"{names[(r.dataset, r.forget_class)].split(' ', 1)[1]}, batch {int(r.batch_size)}: "
                   f"$D_r$ {r.post_retain:.1f}" for _, r in dflt.sort_values(
                       ["dataset", "forget_class", "batch_size"]).iterrows())
    body = r"""\begin{table}[t]
\centering
\caption{Held-out classes on which SSD's own paper reports failures. Each method
runs at the configuration it selected on the five main forget classes
(transfer, the headline), with $D_r/D_f$ and $\Delta$; ``oracle'' is its best
$\Delta$ over its whole grid on that class. These classes were chosen because a
paper reports SSD failing on them, so they are kept out of every five-class mean.
At SSD's published default ($\alpha=10$, $\lambda=1$) the failure reproduces at
some importance batch sizes: """ + dl + r""".}
\label{tab:e11}
\scriptsize
\setlength{\tabcolsep}{2.8pt}
\begin{tabular}{@{}lcccccccccc@{}}
\toprule
& Retrain & \multicolumn{3}{c}{SSD} & \multicolumn{3}{c}{LFSSD} & \multicolumn{3}{c}{UnAct (ours)} \\
\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(l){9-11}
Class & $D_r$ & $D_r/D_f$ & $\Delta$ & oracle & $D_r/D_f$ & $\Delta$ & oracle & $D_r/D_f$ & $\Delta$ & oracle \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_e11.tex", body, src)


# ==========================================================================
# Relearning (E7, and E5c when present)
# ==========================================================================
def table_relearn():
    e7 = load_e7()
    src = "e7_relearn.csv"
    lines = []
    for ds in DATASETS:
        cells = []
        for m in [1, 5, 25]:
            s = e7[(e7.dataset == ds) & (e7.relearn_m == m) & (e7.step == 10)].set_index("method")
            for meth in ["gold", "ssd", "unact"]:
                cells.append(f"{s.loc[meth, 'd_f']:.1f}")
                num(f"numRelearnDf{M_WORD[meth]}{DS_WORD[ds]}M{ {1:'one',5:'five',25:'twentyfive'}[m] }".replace(" ", ""),
                    s.loc[meth, "d_f"], src, "{:.1f}")
            cells.append(f"{s.loc['gold', 'd_r']:.1f}")
        lines.append(f"{DATASET_LABEL[ds]} & " + " & ".join(cells) + r" \\")
    g50 = e7[(e7.method == "gold") & (e7.step == 50)]
    for _, r in g50.iterrows():
        num(f"numRelearnGoldDrStepfifty{DS_WORD[r.dataset]}M{ {1:'one',5:'five',25:'twentyfive'}[r.relearn_m] }".replace(" ", ""),
            r.d_r, src, "{:.1f}")
    body = r"""\begin{table}[t]
\centering
\caption{Forget accuracy (\%) after 10 relearning steps, each on $m$ forget
images mixed $4{:}1$ with retain images (SGD, lr 0.01), mean over the five forget
classes. The retrained model is the reference: it never saw the class, so any
forget accuracy it gains is learned from the $m$ images alone. ``Ret.\ $D_r$'' is
the retrained model's own retain accuracy at step 10; at $m=1$ the probe degrades
it substantially, so small-$m$ curves mix relearning with damage
(Figure~\ref{fig:relearn-curves}).}
\label{tab:relearn}
\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lcccccccccccc@{}}
\toprule
& \multicolumn{4}{c}{$m=1$} & \multicolumn{4}{c}{$m=5$} & \multicolumn{4}{c}{$m=25$} \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(l){10-13}
Dataset & Retrain & SSD & UnAct & Ret.\ $D_r$ & Retrain & SSD & UnAct & Ret.\ $D_r$ & Retrain & SSD & UnAct & Ret.\ $D_r$ \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_relearn.tex", body, src)
    d = load_e5c()
    if d is not None and len(d):
        for meth in ["gold", "ssd", "unact"]:
            t = d[(d.method == meth)]
            num(f"numVitRelearnClasses{M_WORD[meth]}", str(t.forget_class.nunique()),
                "e5c_vit_relearn.csv (lr 5e-4)")


# ==========================================================================
# Sensitivity and grids
# ==========================================================================
def _worst_one_step(grid, axes, selected):
    q = dict(zip(axes, selected))
    mask = np.ones(len(grid), bool)
    for a, v in q.items():
        mask &= (grid[a] == v).values
    base = grid[mask].score.iloc[0]
    worst, where = base, None
    for a in axes:
        vals = sorted(grid[a].unique())
        i = vals.index(q[a])
        for j in (i - 1, i + 1):
            if not 0 <= j < len(vals):
                continue
            r = dict(q); r[a] = vals[j]
            m = np.ones(len(grid), bool)
            for k, v in r.items():
                m &= (grid[k] == v).values
            sc = grid[m].score.iloc[0]
            if sc > worst:
                worst, where = sc, (a, vals[j])
    return base, worst, where


def table_sensitivity():
    e1, e9, e6 = load_e1(), load_e9_grid(), load_e6()
    axmap = {"alpha": "\\alpha", "lambda": "\\lambda", "batch_size": "\\mathrm{batch}",
             "percentile": "p", "gamma": "\\gamma", "iters": "k"}
    rows = []
    src = "e1_ssd_tune.csv + e9_lfssd_tune.csv + e6_unact_grid.csv"
    for ds in DATASETS:
        for grid, axes, sel, lab, key in [
            (e1[e1.dataset == ds], ["alpha", "lambda", "batch_size"], SSD_SELECTED[ds], "SSD", "ssd"),
            (e9[e9.dataset == ds], ["alpha", "lambda", "batch_size"], LFSSD_SELECTED[ds], "LFSSD", "lfssd"),
            (e6[e6.dataset == ds], ["percentile", "gamma", "iters"], UNACT_SELECTED[ds], "UnAct", "unact"),
        ]:
            g = grid.reset_index(drop=True)
            base, worst, where = _worst_one_step(g, axes, sel)
            s = g.score.values
            w = f"${axmap[where[0]]}\\!=\\!{where[1]:g}$" if where else "---"
            first = DATASET_LABEL[ds] if key == "ssd" else ""
            rows.append(f"{first} & {lab} & {len(s)} & {base:.3f} & {np.median(s):.1f} & "
                        f"{100 * (s <= 1).mean():.0f}\\% & {100 * (s <= 5).mean():.0f}\\% & "
                        f"{worst / base:.0f}$\\times$ & {w} \\\\")
            num(f"numOneStep{M_WORD[key]}{DS_WORD[ds]}", worst / base, src, "{:.0f}")
            num(f"numFracLeOne{M_WORD[key]}{DS_WORD[ds]}", 100 * (s <= 1).mean(), src, "{:.0f}")
        rows.append(r"\addlinespace[2pt]")
    body = r"""\begin{table}[t]
\centering
\caption{Hyperparameter sensitivity over each method's own grid
($N$ configurations, each averaged over the five forget classes). \emph{Best}
and \emph{median} are $\Delta$ over the grid. The last two columns report the
largest $\Delta$ reachable by moving \emph{one} grid step along a single axis from
the selected configuration, as a multiple of the selected $\Delta$. Every method
has a sharp failure boundary somewhere.}
\label{tab:sensitivity}
\small
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}llccccrrl@{}}
\toprule
Dataset & Method & $N$ & Best $\Delta$ & Median $\Delta$ & $\Delta\!\leq\!1$ & $\Delta\!\leq\!5$ & \multicolumn{2}{c}{Worst single step} \\
\midrule
""" + "\n".join(rows[:-1]) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_sensitivity.tex", body, src)


def table_selectivity():
    e8 = load_e8()
    rows = []
    for ds in DATASETS:
        s = e8[(e8.dataset == ds) & (e8.percentile == 75)].iloc[0]
        rows.append(f"{DATASET_LABEL[ds]} & {int(s.num_classes)} & "
                    f"{pm(s.sel, s.sel_sd, 3)} & {pm(s.forget_mass, s.forget_mass_sd, 1)} & "
                    f"{pm(s.retain_mass, s.retain_mass_sd, 1)} & "
                    f"{pm(s.ratio, s.ratio_sd, 2)} \\\\")
    body = r"""\begin{table}[t]
\centering
\caption{Class selectivity of the selected channels at a fixed $p=75$, measured
on the $512$-channel output of the last residual block. These are forward-pass
statistics and no weight is modified. Per channel, $s=(a_f-a_r)/(a_f+a_r)$,
where $a_f$ and $a_r$ are mean activations on the forget and retain sets. Forget
and retain mass are the fractions of each set's total activation that the
selected channels carry. Mean $\pm$ s.d.\ over the five forget classes.}
\label{tab:selectivity}
\small
\begin{tabular}{@{}lccccc@{}}
\toprule
Dataset & Classes & Selectivity $s$ & Forget mass (\%) & Retain mass (\%) & Ratio \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_selectivity.tex", body, "e8_selectivity.csv")


def _alpha_grid_table(grid, sel, name, label, method, src):
    blocks = []
    for ds in DATASETS:
        a, l, b = sel[ds]
        p = (grid[(grid.dataset == ds) & (grid["lambda"] == l)]
             .pivot(index="alpha", columns="batch_size", values="score"))
        lines = [f"{i:g} & " + " & ".join(
            (f"\\textbf{{{v:.2f}}}" if (i == a and c == b) else f"{v:.2f}")
            for c, v in row.items()) + r" \\" for i, row in p.iterrows()]
        blocks.append((f"{DATASET_LABEL[ds]} ($\\lambda={l:g}$)",
                       " & ".join(str(c) for c in p.columns), "\n".join(lines)))
    body = [r"""\begin{table}[t]
\centering
\caption{Complete """ + method + r""" grid, $\Delta$ averaged over the five
forget classes, at each dataset's selected $\lambda$ (rows: $\alpha$, columns:
importance batch size). The selected operating point is in bold; the full
$\lambda$ axis is in the results file. $\alpha<5$ lies outside the range SSD's
paper reports and was never selected.}
\label{""" + label + r"""}
\scriptsize
"""]
    for title, cols, rows in blocks:
        body.append(r"\begin{minipage}{0.32\textwidth}\centering" + "\n" + f"{title}\\\\[2pt]\n"
                    + r"\begin{tabular}{rccc}" + "\n\\toprule\n"
                    + f"$\\alpha$ & {cols} \\\\\n\\midrule\n{rows}\n"
                    + "\\bottomrule\n\\end{tabular}\n\\end{minipage}\\hfill\n")
    body.append("\\end{table}\n")
    write(name, "".join(body), src)


def table_grids_appendix():
    _alpha_grid_table(load_e1(), SSD_SELECTED, "tab_ssd_grid.tex", "tab:ssd-grid",
                      "SSD", "e1_ssd_tune.csv")
    _alpha_grid_table(load_e9_grid(), LFSSD_SELECTED, "tab_lfssd_grid.tex",
                      "tab:lfssd-grid", "LFSSD", "e9_lfssd_tune.csv")
    e6 = load_e6()
    blocks = []
    for ds in DATASETS:
        p_, g_, k_ = UNACT_SELECTED[ds]
        q = (e6[(e6.dataset == ds) & (e6.gamma == g_)]
             .pivot(index="percentile", columns="iters", values="score"))
        lines = [f"{i:g} & " + " & ".join(
            (f"\\textbf{{{v:.2f}}}" if (i == p_ and c == k_) else f"{v:.2f}")
            for c, v in row.items()) + r" \\" for i, row in q.iterrows()]
        blocks.append((f"{DATASET_LABEL[ds]} ($\\gamma={g_:g}$)",
                       " & ".join(str(c) for c in q.columns), "\n".join(lines)))
    body = [r"""\begin{table}[t]
\centering
\caption{Complete UnAct grid, $\Delta$ averaged over the five forget
classes, at each dataset's selected $\gamma$ (rows: $p$, columns: rounds $k$).
Selected operating point in bold. The usable region runs diagonally in $(p,k)$:
raising $p$ and raising $k$ trade off at roughly constant coverage
(Eq.~\ref{eq:coverage}). The full $\gamma$ axis is in the results file.}
\label{tab:unact-grid}
\scriptsize
"""]
    for title, cols, rows in blocks:
        body.append(r"\begin{minipage}{0.32\textwidth}\centering" + "\n" + f"{title}\\\\[2pt]\n"
                    + r"\begin{tabular}{rcccc}" + "\n\\toprule\n"
                    + f"$p$ & \\multicolumn{{4}}{{c}}{{rounds $k$}} \\\\\n"
                    + f" & {cols} \\\\\n\\midrule\n{rows}\n"
                    + "\\bottomrule\n\\end{tabular}\n\\end{minipage}\\hfill\n")
    body.append("\\end{table}\n")
    write("tab_unact_grid.tex", "".join(body), "e6_unact_grid.csv")


# ==========================================================================
# Further numbers quoted in the prose (ratios, extremes, checks)
# ==========================================================================
N_WORD = {1: "one", 5: "five", 10: "ten", 25: "twentyfive", 100: "hundred",
          500: "fivehundred"}


def numbers_extra():
    # --- forget-set size: ratios at n = 5, from the unrounded means -------------
    data = load_e3_all()
    src = "e3_forget_size.csv (unact, ssd) + e3_lfssd_forget_size.csv"
    for ds in DATASETS:
        u = data["unact"][data["unact"].dataset == ds].set_index("forget_n").score
        for m in ("ssd", "lfssd"):
            o = data[m][data[m].dataset == ds].set_index("forget_n").score
            num(f"numRatio{M_WORD[m]}UnAct{DS_WORD[ds]}Nfive", o.loc[5] / u.loc[5], src, "{:.0f}")
            num(f"numRatio{M_WORD[m]}UnAct{DS_WORD[ds]}Ntwentyfive", o.loc[25] / u.loc[25], src, "{:.0f}")
    # Largest per-class retain drop over every n, for SSD and LFSSD pooled.
    raw = load_e3_raw()
    raw["drop"] = raw.gold_retain - raw.post_retain
    num("numWorstDropBaselinesMax", raw[raw.method.isin(["ssd", "lfssd"])]["drop"].max(), src, "{:.0f}")
    num("numWorstDropUnActMax", raw[raw.method == "unact"]["drop"].max(), src)

    # --- full-class table: largest MIA of any unlearning method -----------------
    m = load_main()
    um = m[m.method.isin(METHODS)]
    num("numMIAMaxUnlearn", 100 * um.mia.max(), "e2_main_table_l4.csv + e9_baselines.csv", "{:.1f}")

    # --- sequential requests: per-order extremes -------------------------------
    seq, _ = load_e4_sequences(verbose=False)
    src = "e4_multiclass.csv + e4b_seq_orders.csv (selected configs)"
    un = seq[(seq.method == "unact") & seq.dataset.isin(["cifar10", "cifar20"])]
    num("numSeqDfMaxUnActCtenCtwenty", un.post_forget.max(), src, "{:.1f}")
    for ds in DATASETS:
        t = seq[(seq.method == "ssd") & (seq.dataset == ds) & (seq.request == 5)]
        num(f"numSeqDfMinOrderSSD{DS_WORD[ds]}Rfive", t.post_forget.min(), src, "{:.1f}")
        num(f"numSeqDfMaxOrderSSD{DS_WORD[ds]}Rfive", t.post_forget.max(), src, "{:.1f}")
    t = seq[(seq.method == "unact") & (seq.dataset == "cifar100")]
    per = t.groupby("request").post_retain.mean()
    num("numSeqDrPerRequestUnActChundred", (per.loc[1] - per.loc[5]) / 4, src, "{:.1f}")

    # --- ViT: retain gap and ratio ---------------------------------------------
    u, s = load_vit()
    scope, p, g, k = VIT_UNACT
    un = u[(u.scope == scope) & (u.percentile == p) & (u.gamma == g) & (u.iters == k)]
    src = "e5b_vit_explore.csv (profile_n 0) + e5b_vit_ssd_explore.csv (eval_retain_n 0)"
    num("numVitDrGapUnAct", un.gold_retain.mean() - un.post_retain.mean(), src, "{:.1f}")
    num("numVitRatioSSDUnAct", s.score.mean() / un.score.mean(), src, "{:.1f}")

    # --- selectivity at p = 75 (forget / retain activation mass) ----------------
    e8 = load_e8()
    for ds in DATASETS:
        r = e8[(e8.dataset == ds) & (e8.percentile == 75)].iloc[0]
        num(f"numSelRatio{DS_WORD[ds]}", r.ratio, "e8_selectivity.csv")

    # --- coverage bound (Eq. coverage) over the UnAct grid ----------------------
    raw6 = pd.read_csv(os.path.join(os.path.dirname(TABDIR), "..", "results",
                                    "e6_unact_grid.csv"))
    meas = raw6.cum_coverage_pct.values
    kmn = np.minimum(100.0, raw6.iters.values * raw6.units_per_round.values / 512 * 100)
    src = "e6_unact_grid.csv"
    num("numCoverageRuns", str(len(raw6)), src)
    num("numCoverageExceedNaive", str(int((meas > raw6.coverage_bound_pct.values + 1e-6).sum())), src)
    # cum_coverage_pct is stored to two decimals, so compare at that resolution.
    num("numCoverageExceedKmN", str(int((meas > kmn + 0.01).sum())), src)

    # --- label-free check (constant labels) --------------------------------------
    lf = pd.read_csv(os.path.join(os.path.dirname(TABDIR), "..", "results",
                                  "e9_labelfree_check.csv"))
    src = "e9_labelfree_check.csv"
    for meth in ("unact", "lfssd"):
        t = lf[lf.method == meth]
        num(f"numLabelFreeIdentical{M_WORD[meth]}", str(int(t.bit_identical.sum())), src)
        num(f"numLabelFreeDatasets{M_WORD[meth]}", str(int(t.dataset.nunique())), src)
    t = lf[lf.method == "ssd"]
    num("numLabelFreeSSDDiffMinM", t.n_params_differing.min() / 1e6, src, "{:.1f}")
    num("numLabelFreeSSDDiffMaxM", t.n_params_differing.max() / 1e6, src, "{:.1f}")

    # --- ViT relearn probe (lr 5e-4), classes complete for every method ---------
    d = load_e5c()
    if d is not None and len(d):
        full = d.groupby(["method", "forget_class", "relearn_m"]).step.nunique()
        full = full[full == 7].reset_index()
        per_m = full.groupby(["forget_class", "relearn_m"]).method.nunique()
        common_cls = sorted({c for (c, mm), n in per_m.items() if n == 3 and mm == 5})
        src = "e5c_vit_relearn.csv (lr 5e-4)"
        num("numVitRelearnClassesCommon", str(len(common_cls)), src)
        for meth in ("gold", "ssd", "unact"):
            for step, sw in ((5, "Sfive"), (10, "Sten")):
                t = d[(d.method == meth) & (d.relearn_m == 5) & (d.step == step)
                      & d.forget_class.isin(common_cls)]
                if len(t):
                    num(f"numVitRelearnDf{M_WORD[meth]}Mfive{sw}", t.d_f.mean(), src, "{:.1f}")


# ==========================================================================
# ViT forget-set size (E5d) -- only once all 70 rows are present
# ==========================================================================
def numbers_vit_forget_size():
    from common import load_e5d
    agg, raw = load_e5d()
    if agg is None:
        print("  skip ViT forget-size macros: results/e5d_vit_forget_size.csv incomplete")
        return
    src = "e5d_vit_forget_size.csv"
    for meth in ("unact", "ssd"):
        a = agg[agg.method == meth].set_index("forget_n")
        for n, w in N_WORD.items():
            if n in a.index:
                num(f"numVitFsDelta{M_WORD[meth]}N{w}", a.loc[n, "score"], src)
                num(f"numVitFsMinDr{M_WORD[meth]}N{w}", a.loc[n, "d_r_min"], src, "{:.1f}")
        full = a.index.max()
        num(f"numVitFsDelta{M_WORD[meth]}Nfull", a.loc[full, "score"], src)
        r = raw[raw.method == meth]
        num(f"numVitFsWorstDrop{M_WORD[meth]}", (r.gold_retain - r.post_retain).max(), src, "{:.1f}")

    # Wall-clock per request (one run per class; classes 0/2/3/5 on the L4, class 8
    # on the A10, both methods paired on the same card). SSD's method_time_s includes
    # its full-training-set importance pass; that pass does not depend on n, so its
    # time with the pass precomputed is t(n) - t(n=1), up to the ~1 s forget pass at n=1.
    t = raw.pivot_table(index=["forget_class", "forget_n"], columns="method",
                        values="method_time_s").reset_index()
    full = t.groupby("forget_class").forget_n.transform("max") == t.forget_n
    one = t[t.forget_n == 1].set_index("forget_class")
    tf = t[full].set_index("forget_class")
    ssd_amort = tf.ssd - one.ssd
    num("numVitFsTimeUnActFull", tf.unact.mean(), src, "{:.0f}")
    num("numVitFsTimeSSDColdFull", tf.ssd.mean(), src, "{:,.0f}")
    num("numVitFsTimeSSDAmortFull", ssd_amort.mean(), src, "{:.0f}")
    num("numVitFsTimeSSDImportance", one.ssd.mean(), src, "{:,.0f}")
    num("numVitFsSpeedupCold", (tf.ssd / tf.unact).mean(), src, "{:.0f}")
    num("numVitFsSpeedupAmort", (ssd_amort / tf.unact).mean(), src, "{:.1f}")
    num("numVitFsTimeUnActNfive", t[t.forget_n == 5].unact.mean(), src, "{:.1f}")


# ==========================================================================
def write_numbers():
    seen = {}
    lines = []
    for name, v, src in NUMBERS:
        if name in seen:
            if seen[name] != v:
                raise ValueError(f"macro {name} defined twice with {seen[name]} and {v}")
            continue
        seen[name] = v
        lines.append(f"\\newcommand{{\\{name}}}{{{v}}}  % {src}")
    with open(os.path.join(TABDIR, "numbers.tex"), "w", encoding="utf-8") as f:
        f.write("%% Generated by paper/make_tables.py -- every number quoted in the prose.\n")
        f.write("%% \\input{tables/numbers} in the preamble, then write e.g. \\numDeltaCtenUnAct.\n")
        f.write("\n".join(lines) + "\n")
    print(f"  wrote tables/numbers.tex ({len(lines)} macros)")


def main():
    NUMBERS.clear()
    table_main()
    table_vit()
    table_main_full()
    table_data_efficiency()
    table_cost()
    table_multiclass()
    table_sequential()
    table_vit_variants()
    table_e11()
    table_relearn()
    table_sensitivity()
    table_selectivity()
    table_grids_appendix()
    numbers_extra()
    numbers_vit_forget_size()
    write_numbers()


if __name__ == "__main__":
    main()
